default['nodejs']['user'] = "vagrant"
default['nodejs']['group'] = "vagrant"
default['nodejs']['version'] = "v0.10.26"
default['nodejs']['ndenv_url'] = "https://github.com/riywo/ndenv"
default['nodejs']['node-build_url'] = "https://github.com/riywo/node-build"
