default['nodejs']['user'] = "vagrant"
default['nodejs']['group'] = "vagrant"
default['nodejs']['version'] = "2.1.2"
default['nodejs']['ndenv_url'] = "https://github.com/riywo/ndenv"
default['nodejs']['node-build_url'] = "https://github.com/riywo/node-build"
